apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: default
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS times (
      id SERIAL PRIMARY KEY,
      timestamp TIMESTAMP NOT NULL
    );