apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      initContainers:
      - name: db-init
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "timestamps"
        volumeMounts:
        - name: db-init-script
          mountPath: /docker-entrypoint-initdb.d/
      containers:
      - name: database
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "timestamps"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-init-script
          mountPath: /docker-entrypoint-initdb.d/
    volumes:
    - name: db-init-script
      configMap:
        name: db-init-script
